<a href="https://colab.research.google.com/github/yoloaryan/Feature_extraction/blob/main/Feature_extraction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
#loading of the data

In [ ]:
df=pd.read_csv(r'anime.csv')

In [ ]:
df.head()

   Rank                                              Title  Score
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05

In [ ]:
#New column for the episode count

In [ ]:
df.loc[1]

Rank                                                     2
Title    Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...
Score                                                 9.07
Name: 1, dtype: object

In [ ]:
df.loc[2]

Rank                                                     3
Title    Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...
Score                                                 9.06
Name: 2, dtype: object

In [ ]:
df.loc[2]['Title']

'Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 - Dec 2022474,138 members'

In [ ]:
def extract_episodes(txt):
  check=False
  data=""
  for i in txt:
    if i == ")":
      check =False
      return data
    if check ==True:
      data =data + i
    if i == '(':
      check =True

In [ ]:
df ["Title"].apply(extract_episodes)

0      64 eps
1      24 eps
2      13 eps
3      51 eps
4      10 eps
5      51 eps
6       1 eps
7     148 eps
8      13 eps
9      13 eps
10      2 eps
11    110 eps
12     13 eps
13     13 eps
14     12 eps
15    201 eps
16      1 eps
17     22 eps
18     24 eps
19     25 eps
20      1 eps
21      1 eps
22      7 eps
23     14 eps
24     74 eps
25      1 eps
26      1 eps
27     12 eps
28      1 eps
29     24 eps
30     23 eps
31     12 eps
32     26 eps
33     13 eps
34     16 eps
35     11 eps
36      1 eps
37     11 eps
38     10 eps
39      1 eps
40     26 eps
41     12 eps
42     75 eps
43     26 eps
44     26 eps
45     24 eps
46     10 eps
47     12 eps
48     12 eps
49      4 eps
Name: Title, dtype: object

In [ ]:
df["Episodes"] = df ["Title"].apply(extract_episodes)

In [ ]:
df

    Rank                                              Title  Score Episodes
0      1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10   64 eps
1      2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07   24 eps
2      3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06   13 eps
3      4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06   51 eps
4      5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05   10 eps
5      6  Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...   9.04   51 eps
6      7  Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...   9.04    1 eps
7      8  Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...   9.04  148 eps
8      9  Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...   9.04   13 eps
9     10  Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...   9.03   13 eps
10    11  Shingeki no Kyojin: The Final Season - Kankets...   9.03    2 eps
11    12  Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...   9.02  110 eps
12    13  Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (...   8.99   13 eps
13    14  Fruits Basket: The FinalTV (13 eps)Apr 2021 - ...   8.99   13 eps
14    15  Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 ...   8.98   12 eps
15    16  GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...   8.94  201 eps
16    17  Koe no KatachiMovie (1 eps)Sep 2016 - Sep 2016...   8.94    1 eps
17    18  3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 ...   8.93   22 eps
18    19  Clannad: After StoryTV (24 eps)Oct 2008 - Mar ...   8.93   24 eps
19    20  Code Geass: Hangyaku no Lelouch R2TV (25 eps)A...   8.91   25 eps
20    21  Gintama Movie 2: Kanketsu-hen - Yorozuya yo Ei...   8.91    1 eps
21    22  Violet Evergarden MovieMovie (1 eps)Sep 2020 -...   8.89    1 eps
22    23  Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 -...   8.88    7 eps
23    24  Gintama.: Shirogane no Tamashii-hen - Kouhan-s...   8.88   14 eps
24    25  MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...   8.87   74 eps
25    26  Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 2016...   8.84    1 eps
26    27  Kaguya-sama wa Kokurasetai: First Kiss wa Owar...   8.84    1 eps
27    28  Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022...   8.83   12 eps
28    29  The First Slam DunkMovie (1 eps)Dec 2022 - Dec...   8.83    1 eps
29    30  Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun...   8.82   24 eps
30    31  Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 -...   8.82   23 eps
31    32  Gintama.: Shirogane no Tamashii-henTV (12 eps)...   8.81   12 eps
32    33  Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 20...   8.81   26 eps
33    34  Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 201...   8.80   13 eps
34    35  Shingeki no Kyojin: The Final SeasonTV (16 eps...   8.80   16 eps
35    36  Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 20...   8.79   11 eps
36    37  Kizumonogatari III: Reiketsu-henMovie (1 eps)J...   8.79    1 eps
37    38  "Oshi no Ko"TV (11 eps)Apr 2023 - Jun 2023645,...   8.79   11 eps
38    39  Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...   8.78   10 eps
39    40  Sen to Chihiro no KamikakushiMovie (1 eps)Jul ...   8.78    1 eps
40    41  Monogatari Series: Second SeasonTV (26 eps)Jul...   8.77   26 eps
41    42  Shingeki no Kyojin: The Final Season Part 2TV ...   8.77   12 eps
42    43  Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...   8.76   75 eps
43    44  Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,79...   8.75   26 eps
44    45  Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 20...   8.75   26 eps
45    46  Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,40...   8.74   24 eps
46    47  Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 20...   8.73   10 eps
47    48  Shouwa Genroku Rakugo Shinjuu: Sukeroku Futata...   8.72   12 eps
48    49  Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 20...   8.71   12 eps
49    50  Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...   8.71    4 eps

In [ ]:
df["Episodes"] = df["Title"].apply(extract_episodes)

In [ ]:
df['Episodes'].str.replace("eps","")

0      64
1      24
2      13
3      51
4      10
5      51
6       1
7     148
8      13
9      13
10      2
11    110
12     13
13     13
14     12
15    201
16      1
17     22
18     24
19     25
20      1
21      1
22      7
23     14
24     74
25      1
26      1
27     12
28      1
29     24
30     23
31     12
32     26
33     13
34     16
35     11
36      1
37     11
38     10
39      1
40     26
41     12
42     75
43     26
44     26
45     24
46     10
47     12
48     12
49      4
Name: Episodes, dtype: object

In [ ]:
df["Episodes"]=df['Episodes'].str.replace("eps","")

In [ ]:
df

    Rank                                              Title  Score Episodes
0      1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10      64
1      2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07      24
2      3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06      13
3      4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06      51
4      5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05      10
5      6  Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...   9.04      51
6      7  Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...   9.04       1
7      8  Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...   9.04     148
8      9  Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...   9.04      13
9     10  Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...   9.03      13
10    11  Shingeki no Kyojin: The Final Season - Kankets...   9.03       2
11    12  Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...   9.02     110
12    13  Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (...   8.99      13
13    14  Fruits Basket: The FinalTV (13 eps)Apr 2021 - ...   8.99      13
14    15  Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 ...   8.98      12
15    16  GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...   8.94     201
16    17  Koe no KatachiMovie (1 eps)Sep 2016 - Sep 2016...   8.94       1
17    18  3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 ...   8.93      22
18    19  Clannad: After StoryTV (24 eps)Oct 2008 - Mar ...   8.93      24
19    20  Code Geass: Hangyaku no Lelouch R2TV (25 eps)A...   8.91      25
20    21  Gintama Movie 2: Kanketsu-hen - Yorozuya yo Ei...   8.91       1
21    22  Violet Evergarden MovieMovie (1 eps)Sep 2020 -...   8.89       1
22    23  Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 -...   8.88       7
23    24  Gintama.: Shirogane no Tamashii-hen - Kouhan-s...   8.88      14
24    25  MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...   8.87      74
25    26  Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 2016...   8.84       1
26    27  Kaguya-sama wa Kokurasetai: First Kiss wa Owar...   8.84       1
27    28  Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022...   8.83      12
28    29  The First Slam DunkMovie (1 eps)Dec 2022 - Dec...   8.83       1
29    30  Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun...   8.82      24
30    31  Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 -...   8.82      23
31    32  Gintama.: Shirogane no Tamashii-henTV (12 eps)...   8.81      12
32    33  Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 20...   8.81      26
33    34  Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 201...   8.80      13
34    35  Shingeki no Kyojin: The Final SeasonTV (16 eps...   8.80      16
35    36  Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 20...   8.79      11
36    37  Kizumonogatari III: Reiketsu-henMovie (1 eps)J...   8.79       1
37    38  "Oshi no Ko"TV (11 eps)Apr 2023 - Jun 2023645,...   8.79      11
38    39  Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...   8.78      10
39    40  Sen to Chihiro no KamikakushiMovie (1 eps)Jul ...   8.78       1
40    41  Monogatari Series: Second SeasonTV (26 eps)Jul...   8.77      26
41    42  Shingeki no Kyojin: The Final Season Part 2TV ...   8.77      12
42    43  Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...   8.76      75
43    44  Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,79...   8.75      26
44    45  Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 20...   8.75      26
45    46  Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,40...   8.74      24
46    47  Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 20...   8.73      10
47    48  Shouwa Genroku Rakugo Shinjuu: Sukeroku Futata...   8.72      12
48    49  Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 20...   8.71      12
49    50  Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...   8.71       4

In [ ]:

df.loc[0]['Episodes']

'64 '

In [ ]:
#type of
type(df.loc[0]['Episodes'])

str

In [ ]:
#convert into the integer value
df['Episodes'].astype(int)

0      64
1      24
2      13
3      51
4      10
5      51
6       1
7     148
8      13
9      13
10      2
11    110
12     13
13     13
14     12
15    201
16      1
17     22
18     24
19     25
20      1
21      1
22      7
23     14
24     74
25      1
26      1
27     12
28      1
29     24
30     23
31     12
32     26
33     13
34     16
35     11
36      1
37     11
38     10
39      1
40     26
41     12
42     75
43     26
44     26
45     24
46     10
47     12
48     12
49      4
Name: Episodes, dtype: int64

In [ ]:
df

    Rank                                              Title  Score Episodes
0      1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10      64
1      2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07      24
2      3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06      13
3      4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06      51
4      5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05      10
5      6  Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...   9.04      51
6      7  Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...   9.04       1
7      8  Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...   9.04     148
8      9  Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...   9.04      13
9     10  Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...   9.03      13
10    11  Shingeki no Kyojin: The Final Season - Kankets...   9.03       2
11    12  Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...   9.02     110
12    13  Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (...   8.99      13
13    14  Fruits Basket: The FinalTV (13 eps)Apr 2021 - ...   8.99      13
14    15  Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 ...   8.98      12
15    16  GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...   8.94     201
16    17  Koe no KatachiMovie (1 eps)Sep 2016 - Sep 2016...   8.94       1
17    18  3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 ...   8.93      22
18    19  Clannad: After StoryTV (24 eps)Oct 2008 - Mar ...   8.93      24
19    20  Code Geass: Hangyaku no Lelouch R2TV (25 eps)A...   8.91      25
20    21  Gintama Movie 2: Kanketsu-hen - Yorozuya yo Ei...   8.91       1
21    22  Violet Evergarden MovieMovie (1 eps)Sep 2020 -...   8.89       1
22    23  Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 -...   8.88       7
23    24  Gintama.: Shirogane no Tamashii-hen - Kouhan-s...   8.88      14
24    25  MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...   8.87      74
25    26  Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 2016...   8.84       1
26    27  Kaguya-sama wa Kokurasetai: First Kiss wa Owar...   8.84       1
27    28  Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022...   8.83      12
28    29  The First Slam DunkMovie (1 eps)Dec 2022 - Dec...   8.83       1
29    30  Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun...   8.82      24
30    31  Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 -...   8.82      23
31    32  Gintama.: Shirogane no Tamashii-henTV (12 eps)...   8.81      12
32    33  Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 20...   8.81      26
33    34  Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 201...   8.80      13
34    35  Shingeki no Kyojin: The Final SeasonTV (16 eps...   8.80      16
35    36  Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 20...   8.79      11
36    37  Kizumonogatari III: Reiketsu-henMovie (1 eps)J...   8.79       1
37    38  "Oshi no Ko"TV (11 eps)Apr 2023 - Jun 2023645,...   8.79      11
38    39  Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...   8.78      10
39    40  Sen to Chihiro no KamikakushiMovie (1 eps)Jul ...   8.78       1
40    41  Monogatari Series: Second SeasonTV (26 eps)Jul...   8.77      26
41    42  Shingeki no Kyojin: The Final Season Part 2TV ...   8.77      12
42    43  Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...   8.76      75
43    44  Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,79...   8.75      26
44    45  Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 20...   8.75      26
45    46  Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,40...   8.74      24
46    47  Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 20...   8.73      10
47    48  Shouwa Genroku Rakugo Shinjuu: Sukeroku Futata...   8.72      12
48    49  Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 20...   8.71      12
49    50  Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...   8.71       4

In [ ]:
#New coulms for the time stamp

In [ ]:
df.loc[0]['Title']

'Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr 2009 - Jul 20103,218,472 membersManga StoreVolume 1€4.58Preview'

In [ ]:
df.loc[1]['Title']

'Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473,707 members'

In [ ]:
df

    Rank                                              Title  Score Episodes
0      1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10      64
1      2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07      24
2      3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06      13
3      4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06      51
4      5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05      10
5      6  Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...   9.04      51
6      7  Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...   9.04       1
7      8  Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...   9.04     148
8      9  Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...   9.04      13
9     10  Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...   9.03      13
10    11  Shingeki no Kyojin: The Final Season - Kankets...   9.03       2
11    12  Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...   9.02     110
12    13  Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (...   8.99      13
13    14  Fruits Basket: The FinalTV (13 eps)Apr 2021 - ...   8.99      13
14    15  Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 ...   8.98      12
15    16  GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...   8.94     201
16    17  Koe no KatachiMovie (1 eps)Sep 2016 - Sep 2016...   8.94       1
17    18  3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 ...   8.93      22
18    19  Clannad: After StoryTV (24 eps)Oct 2008 - Mar ...   8.93      24
19    20  Code Geass: Hangyaku no Lelouch R2TV (25 eps)A...   8.91      25
20    21  Gintama Movie 2: Kanketsu-hen - Yorozuya yo Ei...   8.91       1
21    22  Violet Evergarden MovieMovie (1 eps)Sep 2020 -...   8.89       1
22    23  Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 -...   8.88       7
23    24  Gintama.: Shirogane no Tamashii-hen - Kouhan-s...   8.88      14
24    25  MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...   8.87      74
25    26  Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 2016...   8.84       1
26    27  Kaguya-sama wa Kokurasetai: First Kiss wa Owar...   8.84       1
27    28  Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022...   8.83      12
28    29  The First Slam DunkMovie (1 eps)Dec 2022 - Dec...   8.83       1
29    30  Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun...   8.82      24
30    31  Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 -...   8.82      23
31    32  Gintama.: Shirogane no Tamashii-henTV (12 eps)...   8.81      12
32    33  Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 20...   8.81      26
33    34  Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 201...   8.80      13
34    35  Shingeki no Kyojin: The Final SeasonTV (16 eps...   8.80      16
35    36  Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 20...   8.79      11
36    37  Kizumonogatari III: Reiketsu-henMovie (1 eps)J...   8.79       1
37    38  "Oshi no Ko"TV (11 eps)Apr 2023 - Jun 2023645,...   8.79      11
38    39  Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...   8.78      10
39    40  Sen to Chihiro no KamikakushiMovie (1 eps)Jul ...   8.78       1
40    41  Monogatari Series: Second SeasonTV (26 eps)Jul...   8.77      26
41    42  Shingeki no Kyojin: The Final Season Part 2TV ...   8.77      12
42    43  Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...   8.76      75
43    44  Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,79...   8.75      26
44    45  Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 20...   8.75      26
45    46  Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,40...   8.74      24
46    47  Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 20...   8.73      10
47    48  Shouwa Genroku Rakugo Shinjuu: Sukeroku Futata...   8.72      12
48    49  Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 20...   8.71      12
49    50  Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...   8.71       4

In [ ]:
def extraction_time(txt):
  check =False
  data = ""
  for i in range(len(txt)):
    if txt[i]== ')':
      for j in range(i+1,i+20):
        data +=txt[j]
      return data

In [ ]:
df['Title'].apply(extraction_time)

0     Apr 2009 - Jul 2010
1     Apr 2011 - Sep 2011
2     Oct 2022 - Dec 2022
3     Apr 2015 - Mar 2016
4     Apr 2019 - Jul 2019
5     Apr 2011 - Mar 2012
6     Jan 2021 - Jan 2021
7     Oct 2011 - Sep 2014
8     Apr 2022 - Jun 2022
9     Oct 2012 - Mar 2013
10    Mar 2023 - May 2023
11    Jan 1988 - Mar 1997
12    Jul 2023 - Aug 2023
13    Apr 2021 - Jun 2021
14    Jan 2017 - Mar 2017
15    Apr 2006 - Mar 2010
16    Sep 2016 - Sep 2016
17    Oct 2017 - Mar 2018
18    Oct 2008 - Mar 2009
19    Apr 2008 - Sep 2008
20    Jul 2013 - Jul 2013
21    Sep 2020 - Sep 2020
22    Aug 2017 - Aug 2017
23    Jul 2018 - Oct 2018
24    Apr 2004 - Sep 2005
25    Aug 2016 - Aug 2016
26    Dec 2022 - Dec 2022
27    Oct 2022 - Dec 2022
28    Dec 2022 - Dec 2022
29    Jan 2023 - Jun 2023
30    Jul 2023 - Aug 2023
31    Jan 2018 - Mar 2018
32    Apr 2020 - Oct 2021
33    Jan 2019 - Apr 2019
34    Dec 2020 - Mar 2021
35    Dec 2021 - Feb 2022
36    Jan 2017 - Jan 2017
37    Apr 2023 - Jun 2023
38    Oct 2016 - Dec 2016
39    Jul 2001 - Jul 2001
40    Jul 2013 - Dec 2013
41    Jan 2022 - Apr 2022
42    Oct 2000 - Mar 2002
43    Apr 1998 - Apr 1999
44    Apr 2022 - Oct 2022
45    Jul 2019 - Dec 2019
46    Oct 2014 - Dec 2014
47    Jan 2017 - Mar 2017
48    Oct 2022 - Dec 2022
49    Feb 1999 - Sep 1999
Name: Title, dtype: object

In [ ]:
df['Total_time']=df['Title'].apply(extraction_time)

In [ ]:
df

,Rank,Title,Score,Episodes,Total_time
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019
5,6,"Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...",9.04,51,Apr 2011 - Mar 2012
6,7,Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...,9.04,1,Jan 2021 - Jan 2021
7,8,Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...,9.04,148,Oct 2011 - Sep 2014
8,9,Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...,9.04,13,Apr 2022 - Jun 2022
9,10,Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...,9.03,13,Oct 2012 - Mar 2013
10,11,Shingeki no Kyojin: The Final Season - Kankets...,9.03,2,Mar 2023 - May 2023
11,12,Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...,9.02,110,Jan 1988 - Mar 1997
12,13,Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (...,8.99,13,Jul 2023 - Aug 2023
13,14,Fruits Basket: The FinalTV (13 eps)Apr 2021 - ...,8.99,13,Apr 2021 - Jun 2021
14,15,"Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 ...",8.98,12,Jan 2017 - Mar 2017
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,201,Apr 2006 - Mar 2010
16,17,Koe no KatachiMovie (1 eps)Sep 2016 - Sep 2016...,8.94,1,Sep 2016 - Sep 2016
17,18,3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 ...,8.93,22,Oct 2017 - Mar 2018
18,19,Clannad: After StoryTV (24 eps)Oct 2008 - Mar ...,8.93,24,Oct 2008 - Mar 2009
19,20,Code Geass: Hangyaku no Lelouch R2TV (25 eps)A...,8.91,25,Apr 2008 - Sep 2008
20,21,Gintama Movie 2: Kanketsu-hen - Yorozuya yo Ei...,8.91,1,Jul 2013 - Jul 2013
21,22,Violet Evergarden MovieMovie (1 eps)Sep 2020 -...,8.89,1,Sep 2020 - Sep 2020
22,23,Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 -...,8.88,7,Aug 2017 - Aug 2017
23,24,Gintama.: Shirogane no Tamashii-hen - Kouhan-s...,8.88,14,Jul 2018 - Oct 2018
24,25,"MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...",8.87,74,Apr 2004 - Sep 2005
25,26,Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 2016...,8.84,1,Aug 2016 - Aug 2016
26,27,Kaguya-sama wa Kokurasetai: First Kiss wa Owar...,8.84,1,Dec 2022 - Dec 2022
27,28,Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022...,8.83,12,Oct 2022 - Dec 2022
28,29,The First Slam DunkMovie (1 eps)Dec 2022 - Dec...,8.83,1,Dec 2022 - Dec 2022
29,30,Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun...,8.82,24,Jan 2023 - Jun 2023
30,31,Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 -...,8.82,23,Jul 2023 - Aug 2023
31,32,Gintama.: Shirogane no Tamashii-henTV (12 eps)...,8.81,12,Jan 2018 - Mar 2018
32,33,Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 20...,8.81,26,Apr 2020 - Oct 2021
33,34,Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 201...,8.80,13,Jan 2019 - Apr 2019
34,35,Shingeki no Kyojin: The Final SeasonTV (16 eps...,8.80,16,Dec 2020 - Mar 2021
35,36,Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 20...,8.79,11,Dec 2021 - Feb 2022
36,37,Kizumonogatari III: Reiketsu-henMovie (1 eps)J...,8.79,1,Jan 2017 - Jan 2017
37,38,"""Oshi no Ko""TV (11 eps)Apr 2023 - Jun 2023645,...",8.79,11,Apr 2023 - Jun 2023
38,39,Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...,8.78,10,Oct 2016 - Dec 2016
39,40,Sen to Chihiro no KamikakushiMovie (1 eps)Jul ...,8.78,1,Jul 2001 - Jul 2001
40,41,Monogatari Series: Second SeasonTV (26 eps)Jul...,8.77,26,Jul 2013 - Dec 2013
41,42,Shingeki no Kyojin: The Final Season Part 2TV ...,8.77,12,Jan 2022 - Apr 2022
42,43,Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...,8.76,75,Oct 2000 - Mar 2002
43,44,"Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,79...",8.75,26,Apr 1998 - Apr 1999
44,45,Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 20...,8.75,26,Apr 2022 - Oct 2022
45,46,"Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,40...",8.74,24,Jul 2019 - Dec 2019
46,47,Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 20...,8.73,10,Oct 2014 - Dec 2014
47,48,Shouwa Genroku Rakugo Shinjuu: Sukeroku Futata...,8.72,12,Jan 2017 - Mar 2017
48,49,Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 20...,8.71,12,Oct 2022 - Dec 2022
49,50,Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...,8.71,4,Feb 1999 - Sep 1999

In [ ]:
import pandas as pd

# Extract start and end dates
df[["Start_Date", "End_Date"]] = df["Title"].str.extract(
    r'([A-Z][a-z]{2} \d{4}) - ([A-Z][a-z]{2} \d{4})'
)

# Convert to datetime
df["Start_Date"] = pd.to_datetime(df["Start_Date"], format="%b %Y")
df["End_Date"] = pd.to_datetime(df["End_Date"], format="%b %Y")

# Calculate total months (including both start and end months)
df["Total_Months"] = (
    (df["End_Date"].dt.year - df["Start_Date"].dt.year) * 12
    + (df["End_Date"].dt.month - df["Start_Date"].dt.month)
    + 1
)

# Display the result
print(df[["Start_Date", "End_Date", "Total_Months"]].head())

  Start_Date   End_Date  Total_Months
0 2009-04-01 2010-07-01            16
1 2011-04-01 2011-09-01             6
2 2022-10-01 2022-12-01             3
3 2015-04-01 2016-03-01            12
4 2019-04-01 2019-07-01             4

In [ ]:
df

,Rank,Title,Score,Episodes,Total_time,Start_Date,End_Date,Total_Months
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010,2009-04-01,2010-07-01,16
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011,2011-04-01,2011-09-01,6
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022,2022-10-01,2022-12-01,3
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016,2015-04-01,2016-03-01,12
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019,2019-04-01,2019-07-01,4
5,6,"Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...",9.04,51,Apr 2011 - Mar 2012,2011-04-01,2012-03-01,12
6,7,Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...,9.04,1,Jan 2021 - Jan 2021,2021-01-01,2021-01-01,1
7,8,Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...,9.04,148,Oct 2011 - Sep 2014,2011-10-01,2014-09-01,36
8,9,Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...,9.04,13,Apr 2022 - Jun 2022,2022-04-01,2022-06-01,3
9,10,Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...,9.03,13,Oct 2012 - Mar 2013,2012-10-01,2013-03-01,6
10,11,Shingeki no Kyojin: The Final Season - Kankets...,9.03,2,Mar 2023 - May 2023,2023-03-01,2023-05-01,3
11,12,Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...,9.02,110,Jan 1988 - Mar 1997,1988-01-01,1997-03-01,111
12,13,Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (...,8.99,13,Jul 2023 - Aug 2023,2023-07-01,2023-08-01,2
13,14,Fruits Basket: The FinalTV (13 eps)Apr 2021 - ...,8.99,13,Apr 2021 - Jun 2021,2021-04-01,2021-06-01,3
14,15,"Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 ...",8.98,12,Jan 2017 - Mar 2017,2017-01-01,2017-03-01,3
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,201,Apr 2006 - Mar 2010,2006-04-01,2010-03-01,48
16,17,Koe no KatachiMovie (1 eps)Sep 2016 - Sep 2016...,8.94,1,Sep 2016 - Sep 2016,2016-09-01,2016-09-01,1
17,18,3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 ...,8.93,22,Oct 2017 - Mar 2018,2017-10-01,2018-03-01,6
18,19,Clannad: After StoryTV (24 eps)Oct 2008 - Mar ...,8.93,24,Oct 2008 - Mar 2009,2008-10-01,2009-03-01,6
19,20,Code Geass: Hangyaku no Lelouch R2TV (25 eps)A...,8.91,25,Apr 2008 - Sep 2008,2008-04-01,2008-09-01,6
20,21,Gintama Movie 2: Kanketsu-hen - Yorozuya yo Ei...,8.91,1,Jul 2013 - Jul 2013,2013-07-01,2013-07-01,1
21,22,Violet Evergarden MovieMovie (1 eps)Sep 2020 -...,8.89,1,Sep 2020 - Sep 2020,2020-09-01,2020-09-01,1
22,23,Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 -...,8.88,7,Aug 2017 - Aug 2017,2017-08-01,2017-08-01,1
23,24,Gintama.: Shirogane no Tamashii-hen - Kouhan-s...,8.88,14,Jul 2018 - Oct 2018,2018-07-01,2018-10-01,4
24,25,"MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...",8.87,74,Apr 2004 - Sep 2005,2004-04-01,2005-09-01,18
25,26,Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 2016...,8.84,1,Aug 2016 - Aug 2016,2016-08-01,2016-08-01,1
26,27,Kaguya-sama wa Kokurasetai: First Kiss wa Owar...,8.84,1,Dec 2022 - Dec 2022,2022-12-01,2022-12-01,1
27,28,Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022...,8.83,12,Oct 2022 - Dec 2022,2022-10-01,2022-12-01,3
28,29,The First Slam DunkMovie (1 eps)Dec 2022 - Dec...,8.83,1,Dec 2022 - Dec 2022,2022-12-01,2022-12-01,1
29,30,Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun...,8.82,24,Jan 2023 - Jun 2023,2023-01-01,2023-06-01,6
30,31,Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 -...,8.82,23,Jul 2023 - Aug 2023,2023-07-01,2023-08-01,2
31,32,Gintama.: Shirogane no Tamashii-henTV (12 eps)...,8.81,12,Jan 2018 - Mar 2018,2018-01-01,2018-03-01,3
32,33,Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 20...,8.81,26,Apr 2020 - Oct 2021,2020-04-01,2021-10-01,19
33,34,Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 201...,8.80,13,Jan 2019 - Apr 2019,2019-01-01,2019-04-01,4
34,35,Shingeki no Kyojin: The Final SeasonTV (16 eps...,8.80,16,Dec 2020 - Mar 2021,2020-12-01,2021-03-01,4
35,36,Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 20...,8.79,11,Dec 2021 - Feb 2022,2021-12-01,2022-02-01,3
36,37,Kizumonogatari III: Reiketsu-henMovie (1 eps)J...,8.79,1,Jan 2017 - Jan 2017,2017-01-01,2017-01-01,1
37,38,"""Oshi no Ko""TV (11 eps)Apr 2023 - Jun 2023645,...",8.79,11,Apr 2023 - Jun 2023,2023-04-01,2023-06-01,3
38,39,Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...,8.78,10,Oct 2016 - Dec 2016,2016-10-01,2016-12-01,3
39,40,Sen to Chihiro no KamikakushiMovie (1 eps)Jul ...,8.78,1,Jul 2001 - Jul 2001,2001-07-01,2001-07-01,1
40,41,Monogatari Series: Second SeasonTV (26 eps)Jul...,8.77,26,Jul 2013 - Dec 2013,2013-07-01,2013-12-01,6
41,42,Shingeki no Kyojin: The Final Season Part 2TV ...,8.77,12,Jan 2022 - Apr 2022,2022-01-01,2022-04-01,4
42,43,Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...,8.76,75,Oct 2000 - Mar 2002,2000-10-01,2002-03-01,18
43,44,"Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,79...",8.75,26,Apr 1998 - Apr 1999,1998-04-01,1999-04-01,13
44,45,Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 20...,8.75,26,Apr 2022 - Oct 2022,2022-04-01,2022-10-01,7
45,46,"Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,40...",8.74,24,Jul 2019 - Dec 2019,2019-07-01,2019-12-01,6
46,47,Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 20...,8.73,10,Oct 2014 - Dec 2014,2014-10-01,2014-12-01,3
47,48,Shouwa Genroku Rakugo Shinjuu: Sukeroku Futata...,8.72,12,Jan 2017 - Mar 2017,2017-01-01,2017-03-01,3
48,49,Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 20...,8.71,12,Oct 2022 - Dec 2022,2022-10-01,2022-12-01,3
49,50,Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...,8.71,4,Feb 1999 - Sep 1999,1999-02-01,1999-09-01,8

In [ ]:
#Anime with the highest score
df[df['Score'] == df['Score'].max()]['Title']

0    Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...
Name: Title, dtype: object

In [ ]:
#Anime with the minimum  score
df[df['Score'] == df['Score'].min()]['Title']

48    Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 20...
49    Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...
Name: Title, dtype: object

In [ ]:
df['Score'].value_counts()

Score
9.04    4
8.79    3
9.06    2
8.99    2
8.93    2
8.91    2
8.94    2
8.82    2
8.81    2
8.84    2
8.83    2
8.88    2
9.03    2
8.75    2
8.77    2
8.71    2
8.78    2
8.80    2
9.10    1
9.07    1
9.05    1
8.89    1
8.98    1
9.02    1
8.87    1
8.76    1
8.74    1
8.73    1
8.72    1
Name: count, dtype: int64

In [ ]:
df['Score'].unique()

array([9.1 , 9.07, 9.06, 9.05, 9.04, 9.03, 9.02, 8.99, 8.98, 8.94, 8.93,
       8.91, 8.89, 8.88, 8.87, 8.84, 8.83, 8.82, 8.81, 8.8 , 8.79, 8.78,
       8.77, 8.76, 8.75, 8.74, 8.73, 8.72, 8.71])

In [ ]:
# Top 5 title
df['Title'].head()

0    Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...
1    Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...
2    Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...
3    Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...
4    Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...
Name: Title, dtype: object

In [ ]:
#Which anime has the highest episode count
df[df['Episodes'] == df['Episodes'].max()]

,Rank,Title,Score,Episodes,Total_time,Start_Date,End_Date,Total_Months
42,43,Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...,8.76,75,Oct 2000 - Mar 2002,2000-10-01,2002-03-01,18

In [ ]:
#which is the longest running anime
df.sort_values(by="Episodes", ascending=False).head(1)

,Rank,Title,Score,Episodes,Total_time,Start_Date,End_Date,Total_Months
42,43,Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...,8.76,75,Oct 2000 - Mar 2002,2000-10-01,2002-03-01,18